# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Jenkins Master Server
  config.vm.define "master" do |master|
    master.vm.box = "nrel/CentOS-6.5-x86_64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.1.10"
    master.vm.network "forwarded_port", guest: 8080, host: 8080
    master.vm.provision "shell", path: "master.sh"
  end

  # Slave Node 1
  config.vm.define "agent1" do |agent1|
    agent1.vm.box = "nrel/CentOS-6.5-x86_64"
    agent1.vm.hostname = "agent1"
    agent1.vm.network "private_network", ip: "192.168.1.20"
    agent1.vm.provision "shell", path: "agent.sh"
  end
end
